### ISSUE TITLE
When uploading Invalid files, error message is not clear

### ISSUE THREAD

**Issue by MaikelGG** [greenpeace/ggw_styleguide#10]
Change icons and layout according to mockup

![img_17122015_090642](https://cloud.githubusercontent.com/assets/5907886/11871553/9e59ef48-a4d0-11e5-80da-79ef61ce2b92.png)

**Comment by MaikelGG** [comment]
The description will be highlighted for 2.5 seconds. Design looks as following:
![screen shot 2015-12-21 at 19 30 43](https://cloud.githubusercontent.com/assets/5907886/11938204/79051744-a819-11e5-8ea6-ab089bcb03bf.jpg)

https://github.com/greenpeace/ggw_styleguide/commit/f67cac2067f746c209b827882a4f75002c614fc3

**Comment by stripthis** [comment]
@Crazylord  can you check the status of this. I can not see the behavior in the demo at the moment. Something maybe related, the file upload in document looks broken on mobile see screenshot

![screen shot 2016-01-20 at 10 12 04](https://cloud.githubusercontent.com/assets/77410/12440123/58d41054-bf5e-11e5-87be-03b5cd1e6937.png)

**Comment by Crazylord** [comment]
@stripthis Maybe you need clear cache. How I see, all looks fine.
