### ISSUE TITLE
Clicking on a primary tab doesn't go anywhere

### ISSUE THREAD

**Issue by MaikelGG** [greenpeace/ggw_styleguide#11]
Remove the accordion on mobile. Make the main navigation tab clickable on desktop. Change the default menu structure to be this: https://docs.google.com/spreadsheets/d/13ij1Htrjp3vM18gOeSrcTVNGS1EgFdBjsk38iL9eFOg/edit#gid=502381136

**Comment by MaikelGG** [comment]
@stripthis 
Please review the code locally https://github.com/greenpeace/ggw_styleguide/tree/feature/update-menu-%2311 merge into develop when approved.

**Comment by stripthis** [comment]
@Crazylord this is not live at the moment. Can you check why?

**Comment by Crazylord** [comment]
Fixed this. Maikel forgot deploy changes on to live:)

**Comment by Crazylord** [comment]
Fixed and deployed to live.
