### ISSUE TITLE
Allow hidding some blocks in the mobile action menu

### ISSUE THREAD

**Issue by stripthis** [greenpeace/ggw_styleguide#13]

**Comment by stripthis** [comment]
Currently all the blocks are used to create the "action menu" under the rules of the mobile breakpoints. However some of these blocks, like the slider (called "featured" in the menu) are not really meaningful or that important on mobile and we would like them not to be shown as an option in the action menu in order to reduce the number of options there.

Possible approach:
- create a rule in the action menu using a html tag property like data-action-menu-hide=true 
- modify the javascript to ignore muted blocks

![screen shot 2015-12-22 at 15 25 29](https://cloud.githubusercontent.com/assets/77410/11952665/42bf46ee-a8c0-11e5-8843-dd5695e47995.png)

**Comment by MaikelGG** [comment]
Suggested idea is live on both homepages

**Comment by stripthis** [comment]
@Crazylord This doesn't seem to be live at the moment (e.g. The tab featured should not be shown). Can you check if it is a regression?

**Comment by Crazylord** [comment]
Fixed this. Maikel forgot deploy changes on to live:)
